global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ports-exporter'
    static_configs:
      - targets: ['host.docker.internal:9151', 'host.docker.internal:9181', 'host.docker.internal:11105', 'host.docker.internal:9189']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['host.docker.internal:9093']

rule_files:
  - "/etc/alertmanager/alert.rules"
