{
 "title": "goservice metrics",
 "tags": [
  "go",
  "production"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(go_info{group=\"production\"},job)"
   }
  ]
 },
 "panels": [
  { "title": "memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "resident memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (process_resident_memory_bytes{group=\"production\",job=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (process_virtual_memory_bytes{group=\"production\",job=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "memory heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "heap inuse bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (go_memstats_heap_inuse_bytes{group=\"production\",job=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "heap inuse objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (go_memstats_heap_objects{group=\"production\",job=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "process cpu seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(process_cpu_seconds_total{group=\"production\",job=\"$service\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (go_goroutines{group=\"production\",job=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (version)(go_info{group=\"production\",job=\"$service\"})"
    }
   ]
  },
  {
   "title": "app state",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 23 },
   "targets": [
    {
     "expr": "sum by (instance, env, version) (olymptrade_app_state{job=\"$service\"})"
    }
   ]
  }
 ]
}